Type id refactor
ketoni/FugDemos pull request #2
Opened 2019-09-14 19:10 UTC by Lehdari

Refactor type id system to provide compile time ids via constexpr interface in separate class.
The new method utilizes macros constructed by CMake but voids the need for component template macros and dummy source files.

2019-09-16 20:56 UTC, tkln requested changes

2019-09-16 20:56 UTC, tkln commented on CMakeLists.txt
> -add_subdirectory(breakout)
Name change of the breakout directory should be in the previous commit, which is currently broken.

2019-09-16 20:56 UTC, tkln commented on CMakeLists.txt
> +            breakout/include
This should be Breakout/include.

2019-09-16 20:56 UTC, tkln commented on CMakeLists.txt
> +            RES_DIRECTORY="${CMAKE_CURRENT_SOURCE_DIR}/breakout"
This should have been changed in the previous commit.

2019-09-16 20:56 UTC, tkln commented on CMakeLists.txt
> -        breakout/include
Same as above.

2019-09-16 20:56 UTC, tkln commented on CMakeLists.txt
> -add_subdirectory(breakout)
Also CMake copies the source tree directory structure into the build folder and on Unix-like systems executables have no file extension. These two factors create a situtaion where we have build/Breakout directory while linker tries (and fails) to create an executable with the exact same name.

2019-09-17 13:22 UTC, Lehdari commented
Changes included into other PR

2019-09-17 13:22 UTC, closed without merging